### ISSUE TITLE
Feature Request: 128Kb ROMs support for ROMS.ZX1

### ISSUE THREAD

**Issue by spark2k06** [kounch/zx123_tool#1]
Some time ago, I made a ROM loader from 128Kb snapshots, for the ZXUno menu:

https://github.com/spark2k06/zxuno/tree/master/loader128

Right now the tool is not able to read or manage ZX1 with 128Kb ROMs.

**Comment by kounch** [comment]
Please take a look to this commit: e54f49bfc9cb36b269a78b56c4d1d367f90dfa55

If all goes well, a new version including it will be available this week

**Comment by spark2k06** [comment]
Tested, it works perfectly. Thanks a lot!

**Comment by kounch** [comment]
Release 3.5.0 is available to download, including this feature.
